### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by kkh0811**
first commit

### CODE REVIEW

**Comment by RyanYizhaoHuang** [comment]
Hi Giho, the SQL file you include in the project contains error when I try to use it to set up the testing database.
1. Every time I set up the database, I need to delete the old one manually, it is not convenient for testing.
2. This error:"directory lookup for the file "C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\HexylogyDB.mdf" failed with the operating system error (The system cannot find the path specified.)." 
Which I don't have the mdf file. Actually, it is not necessary to have that mdf file for us to set up the db. 
Please check the HexylogyDB_v2.sql and fix the problem so the developer can use for SQL to implement.

**Comment by kkh0811** [comment]
1. I am trying to figure making local db like SQL CE or SQLite on our project, but cannot use procedures on local db. still looking for alternation.  

2. Did you use the HexylogyDB_v3.sql??

**Comment by RyanYizhaoHuang** [comment]
Yes, I used V3 to set up the db it showed error.
So, i still working on sql v2

**Comment by kkh0811** [comment]
I solved that error on database and waiting to merge it.
Thanks Ryan

**Comment by taerakwon** [comment]
Cancelled

**Pull request closed without merging**
