### PR TITLE
added localdb

### PR DESCRIPTION
**Pull request by kkh0811**
Added Local DB

### CODE REVIEW

**Comment by kkh0811** [comment]
Please use the connection string below:
public String connectionString = @"Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Users\Giho\Documents\Semester5\Computer Programmer Proj-COMP231_003\COMP231-F2016-GROUP1\PasswordApplication\Hexalogydb.mdf;Integrated Security=True";

and change the filepath to your path..

**Comment by taerakwon** [comment]
@domlau @RyanYizhaoHuang @kkh0811 @mekhaleganesh @prtk15 
This merge will not allow any method inside DatabaseHelper to work (deleteRecord, manupulateCategory, UpdateRecord,addNewCategory)

**Comment by RyanYizhaoHuang** [comment]
@kkh0811 , Giho, when you say: "and change the file path to your path.." that means we still need to modify the connectionString everytime we do pull request, otherwise it will cause conflict because everyone have different path for the project db. It is the similar to the problem we have. Can you use a relative path 
( **like:  ../ .../PasswordApplication\Hexalogydb.mdf** )instead of absolute path?

**Comment by RyanYizhaoHuang** [comment]
@taerakwon , are you mentioning about the functions don't work or the functions code are conflict?

**Comment by taerakwon** [comment]
Giho uses Local DB, and it is bit different.  There is too much conflict as I am merging and you guys are merging.  There is one timeline but there is overlap.  Send me pull request to DEV too because it's not going to be possible if more than one person is merging.

**Comment by taerakwon** [comment]
Send correct pull request to Dev.  You merged your work to Master and requested Master to be merged with Dev

**Pull request closed without merging**
